# Generated by Django 3.1.3 on 2020-11-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='forms',
            field=models.JSONField(blank=True, null=True, verbose_name='Forms'),
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type name')),
                ('slot', models.IntegerField(verbose_name='Type slot')),
                ('type', models.JSONField(verbose_name='Type')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types',
                                              to='pokemons.pokemon', verbose_name='Pokemon')),
            ],
        ),
    ]
